### PR TITLE
fix: component setup

### PR DESCRIPTION
**Pull request by NathanWalker**
Per the docs here:
https://github.com/wwwalkerrun/nativescript-ngx-magic#example

Cheers! 🍻

### CODE REVIEW

**Comment by sonicparke** [comment]
Thanks @NathanWalker!

**Comment by sonicparke** [comment]
@NathanWalker did the {N} version run for you? Getting an error now. Looks like a TypeScript issue maybe but still looking.

```
CONSOLE ERROR file:///app/tns_modules/trace/trace.js:160:30: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
Jan 26 18:05:17 bmcalister nativescript[51149]: CONSOLE ERROR file:///app/tns_modules/trace/trace.js:160:30: ns-renderer: null is not an object (evaluating 'getDOM().defaultDoc')
	
	_document@file:///app/tns_modules/@angular/platform-browser/bundles/platform-browser.umd.js:4408:22
	get
	get
	get
	get
	getInternal
	get@file:///app/tns_modules/@angular/core/bundles/core.umd.js:8898:59
	create@file:///app/tns_modules/@angular/core/bundles/core.umd.js:7685:51
	bootstrap@file:///app/tns_modules/@angular/core/bundles/core.umd.js:8657:67
	forEach@[native code]
	_moduleDoBootstrap@file:///app/tns_modules/@angular/core/bundles/core.umd.js:8486:53
	file:///app/tns_modules/@angular/core/bundles/core.umd.js:8438:49
	invoke@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:190:33
	onInvoke@file:///app/tns_modules/@angular/core/bundles/core.umd.js:4391:47
	invoke@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:189:42
	run@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:83:49
	file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:449:60
	invokeTask@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:223:42
	onInvokeTask@file:///app/tns_modules/@angular/core/bundles/core.umd.js:4382:51
	invokeTask@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:222:54
	runTask@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:123:57
	drainMicroTaskQueue@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:355:42
	promiseReactionJob@[native code]
	UIApplicationMain@[native code]
	start@file:///app/tns_modules/application/application.js:251:30
	bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:68:28
	bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:56:26
	anonymous@file:///app/main.js:4:57
	evaluate@[native code]
	moduleEvaluation@[native code]
	[native code]
	promiseReactionJob@[native code]
error TS5053: Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.
```

**Comment by NathanWalker** [comment]
That last error is normal and can be ignored - yeah ran fine here.
The first error seems odd, try this:
rm-rf nativescript node_modules
npm i 

Then you should be able to run all commands just fine, ng serve, npm run start.ios, etc.

**Comment by sonicparke** [comment]
@NathanWalker Thanks. That worked. Weird. Wish there was a better way to track down how this stuff happens. We're all good now. Thanks!

**Pull request merged**
